### ISSUE TITLE
Why replace a large number of k8s-related dependencies

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tiflow-operator#19]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tiflow-operator/issues)
- Read the documentation:
    - [TiFlow Operator Readme](https://github.com/pingcap/tiflow-operator)

https://github.com/pingcap/tiflow-operator/blob/84e5efd6933e69f8e134f8808e058ca3e6dc3d9a/go.mod#L90

as title

**Comment by arlottang** [comment]
ref: https://github.com/kubernetes/kubernetes/blob/master/go.mod#L120
