### ISSUE TITLE
Optimize : requeue After and requeue Immediately 

### ISSUE THREAD

**Issue by arlottang** [pingcap/tiflow-operator#22]
## Feature Request

**Describe the feature you'd like:**

- For Master not yet started, hope to reconcile after a time, rather than immediately
- For Pod crash, hope to reconcile immediately

**Describe alternatives you've considered:**

- to be

**Comment by lichunzhu** [comment]
Some other expectations:
* For normal operations like creating/upgrading a new tiflow cluster, we should reduce reconcile times.
* For reconcile caused by status update, we should reduce reconcile times. Maybe through some cache methods https://github.com/infinispan/infinispan-operator/pull/515

**Comment by arlottang** [comment]
#32
